### ISSUE TITLE
**Task Management.** As a contributor, I would like to manage my Open edX tasks in a publicly visible and accessible space, in order to collaborate and innovate with others.

### ISSUE THREAD

**Issue by nasthagiri** [openedx/open-edx-proposals#174]
![Screen Shot 2020-12-02 at 8 32 33 PM](https://user-images.githubusercontent.com/6772826/100951952-92c91300-34dd-11eb-95c8-4ca3a07f9505.png)

**Comment by nasthagiri** [comment]
A few points raised thus far in favor of using GitHub Issues:

* Github projects could work for _both_ process and code action items.
* We already using GitHub as a tool.
* It is relatively simple.
* We can ensure discussions are public, and that anyone could raise an issue or comment in the future.
* JIRA is consistently alienating - we get frequent permission errors and don’t understand workflows and the seemingly endless fields.
* We can more easily tag others that are GitHub members.

**Comment by regisb** [comment]
I think @nedbat's criticisms of Github issues that he mentioned during [the last contributors meetup](https://discuss.openedx.org/t/open-edx-contributors-meetup/1450/36) are very relevant. As much as I *hate* Jira, agree with the "consistently alienating" description, and regret the fact that edX abruptly removed all issues from all Open edX projects, I must admit that there are good reasons why edX moved away from Github Issues:

1. The Github issue system is simplistic.
2. It is not well-suited to complex projects that span 300 repositories.
3. When Github issues work well, it's because they target *code* issues -- and the issues that the CC program aims at resolving are not directly related to code.
4. We do not want to allow just anyone to create new Github issues, because issue moderation is a difficult problem. However, AFAIK, it is not possible to define fine-grained issue creation permissions.
5. EdX people are used to tracking issues in Jira; if core committers were to track their issues in a separate tool, it would create yet another separation between the two worlds.

**Comment by nedbat** [comment]
I'm not sure what is expected of me on this issue (it's assigned to me and others).

**Comment by nasthagiri** [comment]
@nedbat I would like for us to make a final decision by end of January on where we're discussing and tracking issues with the Community.  That's what this GitHub issue represents.  In the meantime, we are using GitHub issues for other Core Committer efforts - and we'll have more experience and learnings to include in the decision.

**Comment by nasthagiri** [comment]
Here are a few observations from the past several weeks:

**GitHub Projects/Issues**

- (Plus) There are about 30 comments in total on the 3 Github Issues that were active this month.
- (Plus) Of the contributors, 4 were edXers and 6 were Open edXers.
- (Plus) We were able to tag and pull-in Robert at edX on one of the issues.
- (Minus) By default, the org-wide GitHub project creates "cards" that do not support conversational threads. One needs to convert the "card" to a repo-backed "issue" in order to invite discussion.
- (Note) We are currently using the `open-edx-proposals` repo as the backing repo for our GitHub issues. This required giving Core Committers write access to the repo. GitHub also [proposes having an Issues-only Repo](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-an-issues-only-repository) if we choose.

**Trello**

- (Plus) Seems to be a user-friendly interface and a more common tool for non-developers. For example, our technical writer, Amy, preferred using Trello since she was already familiar with it - rather than learning how to use GitHub Projects.
- (Minus) Not as easy to engage with others for multiple reasons (not everyone has a Trello handle, yet another tool for people to use).

**JIRA**

- (Plus) Has a more extensive feature set.
- (Minus) Very difficult to troubleshoot and continues to have perennial issues that slow down Open edX efforts. (For example: not able to tag folks when needed; not able to assign folks to an issue when needed; basic operations require admin privileges that are shared with a very limited few, even within edX.)

**Comment by nasthagiri** [comment]
Now that we've experienced using GitHub Projects the last several weeks, let's take another poll to see where folks are leaning at this point.
 
/polls 'Use Trello' 'Use JIRA' 'Use GitHub Projects/Issues' 'Need more time to decide' 'Ok with whatever is decided'

**Comment by nasthagiri** [comment]
Now that we've experienced using GitHub Projects the last several weeks, let's take another poll to see where folks are leaning at this point.

[![](https://api.gh-polls.com/poll/01EWDW74YB0BDSRN0S7W3MQDKX/Use%20Trello)](https://api.gh-polls.com/poll/01EWDW74YB0BDSRN0S7W3MQDKX/Use%20Trello/vote)
[![](https://api.gh-polls.com/poll/01EWDW74YB0BDSRN0S7W3MQDKX/Use%20JIRA)](https://api.gh-polls.com/poll/01EWDW74YB0BDSRN0S7W3MQDKX/Use%20JIRA/vote)
[![](https://api.gh-polls.com/poll/01EWDW74YB0BDSRN0S7W3MQDKX/Use%20Github%20Projects%20and%20Issues)](https://api.gh-polls.com/poll/01EWDW74YB0BDSRN0S7W3MQDKX/Use%20Github%20Projects%20and%20Issues/vote)
[![](https://api.gh-polls.com/poll/01EWDW74YB0BDSRN0S7W3MQDKX/Need%20more%20time%20to%20decide)](https://api.gh-polls.com/poll/01EWDW74YB0BDSRN0S7W3MQDKX/Need%20more%20time%20to%20decide/vote)
[![](https://api.gh-polls.com/poll/01EWDW74YB0BDSRN0S7W3MQDKX/Ok%20with%20whatever%20is%20decided)](https://api.gh-polls.com/poll/01EWDW74YB0BDSRN0S7W3MQDKX/Ok%20with%20whatever%20is%20decided/vote)

**Comment by kdmccormick** [comment]
@nasthagiri Whoops, I thought that the poll was a static image, and clicked on "Use Trello" by accident. I meant to vote for GH issues.

**Comment by toxinu** [comment]
> @nasthagiri Whoops, I thought that the poll was a static image, and clicked on "Use Trello" by accident. I meant to vote for GH issues.

Same for me. I voted for Trello by mistake but wanted to vote for GH issues.

**Comment by nasthagiri** [comment]
lol. No worries. I decided to try out the `https://app.gh-polls.com/` poll.  I  can see it has minimal features at this point - like not being able to undo a vote and only supporting anonymous polls.

Thanks for posting the error. We'll subtract from the "Use Trello" and add to "GH Issues".

**Comment by OmarIthawi** [comment]
> > @nasthagiri Whoops, I thought that the poll was a static image, and clicked on "Use Trello" by accident. I meant to vote for GH issues.
> 
> Same for me. I voted for Trello by mistake but wanted to vote for GH issues.

I think I've done the same thing 😅

**Comment by nasthagiri** [comment]
All, Thanks for your input and votes and discussion on this topic.

I'd like to close out this issue at this point. **We will move forward with the majority vote (21 votes) of using GitHub projects for the Open edX community's task management.**

Given this decision, the Core Committer's tasks will remain where they are in the [Core Committer GitHub project](https://github.com/orgs/edx/projects/1). 

I will create a separate task for transferring the tasks from the [community working group's trello board](https://trello.com/b/d8oWzNoy/community-working-group) to GitHub projects.  cc: @antoviaque
