### ISSUE TITLE
Transfer Community Working group's Trello board to GitHub projects.

### ISSUE THREAD

**Issue by nasthagiri** [openedx/open-edx-proposals#183]
Given the decision from https://github.com/edx/open-edx-proposals/issues/174, we'd like to transfer the Trello cards from https://trello.com/b/d8oWzNoy/community-working-group to GitHub projects.

Things to decide:

- [ ] Project location. (It could just be alongside the other existing projects at https://github.com/orgs/edx/projects.)
- [ ] Repo that backs the GitHub project. (It could just be the https://github.com/edx/open-edx-proposals repo.)
- [ ] Granularity of the project. Shall we have a separate project for each working group? (Marketing, BTR, Docs, etc)
- [ ] Access control to the repo - To assign someone to an issue, they must have write access to the repo.

**Comment by nasthagiri** [comment]
@antoviaque @arbrandes @nedbat Would appreciate your thoughts on the decisions above.

@antoviaque Also, when the time comes to transfer the Trello cards, I can help with the labor.

**Comment by antoviaque** [comment]
@nasthagiri Thanks for creating this task!

>  Project location. (It could just be alongside the other existing projects at https://github.com/orgs/edx/projects.)

Sure, sounds good to me :+1: 

> Repo that backs the GitHub project. (It could just be the https://github.com/edx/open-edx-proposals repo.)

Using the OEP repo works on my side :+1: 

> Granularity of the project. Shall we have a separate project for each working group? (Marketing, BTR, Docs, etc)

It's useful to be able to see the current status of the issues on one board imho -- at the very least, the issues that we review together during the community meetup. Is there a way to use filters like on Trello?

Btw, how do we handle the overlap between the groups and the type of issues we would have on the core committer program board, which has scope more or less overall the groups? Maybe we could keep everything in one place for now, and split when/if needed?

> Access control to the repo - To assign someone to an issue, they must have write access to the repo.

Argh - that's actually an issue no? Imho want to be able to assign issues to anyone in the community, but we don't want to give write access to the repo (or even all the issues?) to anyone just showing up, it's a surprising limitation. Edit: Actually, looking into it seems that GitHub recently relaxed this rule - it should now be possible to [assign issues to people who have commented on it](https://github.blog/2019-06-25-assign-issues-to-issue-commenters/) \o/

**Comment by nedbat** [comment]
> Repo that backs the GitHub project. (It could just be the https://github.com/edx/open-edx-proposals repo.)

I would rather that we create a new repo to hold these issues.  If someone comes fresh to the open-edx-proposals repo and takes a look at the issues, they will be confused what they have to do with OEPs.  Repos are easy to make, and we can put a README on it that explains what is going on. It could even be in the openedx GitHub organization.

**Comment by nasthagiri** [comment]
+1 to creating a repo just for keeping issues.  [GitHub recommends this](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-an-issues-only-repository).

It addresses the access control issue as well.

I'm Ok with using either the `openedx` org or the `edx` org.  I'm curious whether it would be confusing for new developers when they arrive at `github.com/edx` and are then asked to go to another org altogether for issues related to the `edx` org.

**Comment by arbrandes** [comment]
Note to followers, particularly @nedbat and @nasthagiri: I've volunteered internally at OpenCraft to execute the actual migration of tickets, once the details are ironed out.  Should I be assigned here, already, or on a new issue in the new repository?

**Comment by nasthagiri** [comment]
@arbrandes Sounds good. Let me know if you need help with the effort.
I also wonder if some tickets are no longer relevant and don't need to be transferred.

**Comment by arbrandes** [comment]
Forgot to close this one.
