### ISSUE TITLE
Leaderboard: docker-compose and deployment cleanup

### ISSUE THREAD

**Issue by pomegranited** [openedx/open-edx-proposals#227]
## Story

"As a leaderboard contributor, I want to clean up the deployment process to make it more robust and repeatable."

## Full description

The original deployment to Heroku was intended to be self-provisioning, and [runs various scripts](https://github.com/openedx/metrics-dashboard/blob/master/entrypoint.sh#L8-L19) to update the projects and identities lists. However, this approach is brittle and makes deployments slow.

@e0d submitted https://github.com/openedx/metrics-dashboard/pull/9 with a `docker-compose.yml` and related config files which can be used as a base to improve the development and deployment processes. 

### References:

* [Running GrimoireLab with docker-compose](https://github.com/chaoss/grimoirelab/tree/master/docker-compose)
* [Heroku: Local Development with Docker Compose](https://devcenter.heroku.com/articles/local-development-with-docker-compose) for details on how to use docker-compose with Heroku.

## Completion Criteria

* PR against https://github.com/openedx/metrics-dashboard which converts the deployment and devstack to use docker-compose and cleans up the repository, removing any unused/unneeded files.
* Secrets / credentials split into a separate repo which can be selectively shared with other contributors to this project.
* Processes/scripts for updating the projects, bots, identities, and organizations configuration documented and separated from the deployment process.

### Documentation updates & improvements criteria

* Updated README explaining how to run the devstack, update the configurations, and deploy a new build to Heroku.

**Comment by pomegranited** [comment]
Comments from Slack: CC @Kelketek 

> e0d: One of the overcomplicated bits I want to remove is how the docker entry point tries to do everything on startup, like refresh the projects, rebuild the identities, it's too fragile.  Should probably just have make commands for that stuff.
> pomegranited: hmm.. isn't that mordred's job? maybe we could move that stuff to a cron/service instead of startup?
> e0d: Maybe mordred does that too, but it definitely schedules all the data retrieval and studies. However, it wants to tell it what to retrieve and study.  The existing entry point was doing things like hitting github to look for any new public repositories.
> pomegranited: oh ok gotcha -- you're talking about our entrypoint.sh file. yep, that stuff should be split out

**Comment by sarina** [comment]
Hi everyone, this issue hasn't been touched since September 2021. Was there any enthusiasm/capacity to pick up on this idea, or should we close the issue?

If we want to keep it I propose moving the issue to https://github.com/openedx/wg-coordination/issues since this issue doesn't pertain to an OEP.

**Comment by Kelketek** [comment]
@sarina I think the project this is referring to is either dead or has been obviated. I'd say go ahead and close it. If someone really needs to, they can port the issue to the new repo.
