### ISSUE TITLE
Leaderboard: Track "hours of effort"

### ISSUE THREAD

**Issue by pomegranited** [openedx/open-edx-proposals#237]
* important for core contributor tracking
* will be imperfect

cf https://github.com/edx/open-edx-proposals/issues/179#issuecomment-826223378

**Comment by pomegranited** [comment]
@antoviaque @adolfo Do you have any ideas on how this metric could be collected?

We could make up a heuristic for discussion/Slack posts, e.g. some number of seconds per word posted.
But for PRs, it's very difficult to gauge, and so we'd need to rely on people's self-reported time. But where/how would they report this? And how would we collect it reliably?

CC @e0d

**Comment by e0d** [comment]
Here's what I was brainstorming.  https://docs.google.com/document/d/1gAnxe2sZcZRBrVWThvfREmsqOWMMVQ6PXFNhRBBL-Wg/edit?usp=sharing

**Comment by antoviaque** [comment]
@pomegranited @e0d Thanks for this! I agree that hours of effort tend to be a good metric :+1:

As for measuring it, a good way could be through self-report, in a public log? The person who knows better how much time something takes is usually the person who does it. There is both an incentive to report it (grow in the leaderboard), but also to be accurate (public time tracking of work items)?

**Comment by sarina** [comment]
Hi everyone, this issue hasn't been touched since September 2021. Was there any enthusiasm/capacity to pick up on this idea, or should we close the issue?

If we want to keep it I propose moving the issue to https://github.com/openedx/wg-coordination/issues since this issue doesn't pertain to an OEP.

**Comment by sarina** [comment]
Closing per https://github.com/openedx/open-edx-proposals/issues/227#issuecomment-2118276888
