### ISSUE TITLE
OEP-19: rST consistent headers

### ISSUE THREAD

**Issue by robrap** [openedx/open-edx-proposals#346]
Do we agree that using consistent headers in rST would be useful? Can we just go with https://docs.openedx.org/en/latest/documentors/references/quick_reference_rst.html as the agreed upon consistent headers?

If so, here are some possible updates:

- [ ] Update OEP-19 to strongly recommended using the consistent headers.
- [ ] Update OEP-19 and any templates it links to to conform with the recommendation.
- [ ] Update OEP-1 and any templates it links to to conform with the recommendation.
- [ ] Create an issue for (https://github.com/openedx/edx-cookiecutters) to confirm with the recommendation, since these will be used in future repos.
- [ ] Are there other repos with templates that are copied? Note: updating other existing rST is nice, but not required.

**Comment by robrap** [comment]
From Peter Pinch:
> I’m not going to argue with consistency, but it’s not clear to me what the alternatives are.
>
> Can you give an example of headers that would need to be changed, to follow this rule? It seems likely my work on the release notes is inconsistent, but I’m not sure sure:
>
> https://github.com/openedx/edx-documentation/blob/master/en_us/open_edx_release_notes/source/nutmeg.rst

There are many alternatives. Here are just some examples of docs that are inconsistent with the current recommendation:
* https://raw.githubusercontent.com/openedx/edx-platform/master/docs/decisions/0001-courses-in-lms.rst
* https://raw.githubusercontent.com/openedx/edx-drf-extensions/master/README.rst
* https://raw.githubusercontent.com/openedx/edx-drf-extensions/master/CHANGELOG.rst

Additionally, I am pretty sure that we need to choose between overline+underline and just underline for H1. I don't think the following are equivalent, and would be considered two different heading levels. This is especially problematic in cases where the README in including the CHANGELOG, and those two files need to be consistent to work correctly.
```
########
H1 Header
########
```
and 
```
H1 Header
########
```

So, when I note that OEP-19 should be update, it may be simply that the overline needs to go away. Note: I personally prefer no overline, and the example I posted in the initial issue doesn't include one.

**Comment by inventhouse** [comment]
I've been using and recommending the styles demo'd in our [mdrst cheatsheet](https://github.com/openedx/mdrst/blob/master/mdrst.rst#headers)
(Including the over-lined H1, and Ned recommended `......` for H5 but it's not included on the cheatsheet as yet)

**Comment by nedbat** [comment]
One note: the https://docs.openedx.org/en/latest/documentors/references/quick_reference_rst.html page says:
> There should be only one H1 heading per topic

I think they mean, "one title per page"?  If not, I don't know what "topic" means, and I don't know why there can't be more than one H1.

Also, @robrap mentioned a README including the Changelog.  RST is flexible about how headings nest, partly to allow for inclusion like that.

**Comment by nedbat** [comment]
I've liked over+under for the title of a page. I think it makes a very clear top-of-page indicator.  

> 3. I think the overline adds another feature of rST that someone needs to learn about who isn't familiar with rST.

Has anyone actually been confused by the overline?

**Comment by robrap** [comment]
> Has anyone actually been confused by the overline?

Who knows. These are weak arguments, but we simply need to choose a standard and go with it. I'm voting for going without the overline, and just explaining my thoughts. We either take a vote, or designate someone to choose their favorite, or flip a coin, etc.

**Comment by nedbat** [comment]
I don't want us to overlook good things about RST because "people have to learn them."  Overlines are not complex, and I don't think anyone has been confused.   If people find them cumbersome, we can skip them, but let's not skip them just because they're different than Markdown.

**Comment by ormsbee** [comment]
> Do we agree that using consistent headers in rST would be useful?

Yes.

> Can we just go with https://docs.openedx.org/en/latest/documentors/references/quick_reference_rst.html as the agreed upon consistent headers?

Works for me.

I have no opinion on overlines.

**Comment by robrap** [comment]
@nedbat: If you feel strongly in favor of the overlines, please make an argument for them. If not, your comments probably aren't helping us reach a decision any faster, but maybe I am missing something.

**Comment by robrap** [comment]
I could see adding something like the following to the reference doc:
```
Heading 5
.........

Heading 5s denote subsections under Heading 4s. Consider breaking up the document to avoid this much nesting.
```

**Comment by sarina** [comment]
As the maintainer of this repo, I say we should follow the recommendations of https://docs.openedx.org/en/latest/documentors/references/quick_reference_rst.html when writing RST across the project. However I don't think anyone has felt strongly enough about this issue to codify it into an OEP. Feel free to re-open if you would like to effect this change!
