### ISSUE TITLE
OEP-55: Change reference link to publicly accessible reference

### ISSUE THREAD

**Issue by giovannicimolin** [openedx/open-edx-proposals#361]
[Reference [5] in the OEP-55](https://github.com/openedx/open-edx-proposals/blame/master/oeps/processes/oep-0055-proc-project-maintainers.rst#L468) links to the article **What Makes a Great Maintainer of Open Source Projects?** behind a paywall (https://www.computer.org/csdl/proceedings-article/icse/2021/029600a982/1sEXoQoeO0E).

Is it possible to replace that URL with one without a paywall, hosted on the website of one of the authors? 
I've found it here: http://gustavopinto.org/lost+found/icse2021.pdf
And it's publicly discoverable from: https://gustavopinto.org/publications/

**Comment by feanil** [comment]
@giovannicimolin good find and thanks for finding the alternative version.  I'm happy to make this PR but also happy to accept a PR for this change from you.  Let me know if you have time to make the PR to update the link or if you'd rather I take care of it.
