### ISSUE TITLE
Update OEP-19 with Recommendations for Private Links in Public Content

### ISSUE THREAD

**Issue by feanil** [openedx/open-edx-proposals#394]
Sometimes it's useful for companies that we work with to be able to cross link public information with related private information that they have.

Put another way, sometimes contributors want to share information where some (most) of it can be public but some small part of it needs to be private to the company they work for.  If we can be clear about how they can go about writing this combo of private/pubilc information.  We can perhaps encourage more of the information to be public while allowing people to connect it easily with their own private information.

I think the recommendation would be something like:

> Linking to private information is fine but should be explicit and clear.  The reader should be able to tell that the writer is aware that most people can't see the content.  This will hopefully give the reader more confidence in the information that's there.  They can trust that the private information is thoughtfully separated because it's not relevant to the community.

**Comment by nedbat** [comment]
I like it.

**Comment by feanil** [comment]
Yea, I'd be curious to hear more as well, when I was envisioning this change, I was expecting it to be used in wiki pages and not necessarily in OEPs.  I can make sure to put in that point of clarification.  Or I'm happy to change my mind if someone has a good reason for it.  I could maybe see a see-also section that had org specific links but even that feels strange in the "Open edX" Proposals.

**Comment by e0d** [comment]
I feel less strongly about wiki pages.  OEPs, on the other hand, are the official, public, documentation of large project decisions.  They are a mechanism for providing transparency and having a public dialogue about important matters.  Private links are non-transparent and, even if the contents are in fact innocuous, raise questions about commitment to genuine transparency.  I cannot image PEPs or RFCs containing links to the private contents of the participants -- at least I've never seen that.

Furthermore, while it might be convenient to have links to private documents in OEPs, it's a classic tragedy of the commons.  If everyone did it, it would be a mess.

**Comment by robrap** [comment]
Thanks @e0d and @feanil. This is helpful nuance. 

Consider also discussing **public docs** (vs private) that are **company specific**, which may still be useful for an OEP, where the company specific decision could be relevant to other companies. See https://open-edx-proposals.readthedocs.io/en/latest/architectural-decisions/oep-0052-arch-event-bus-architecture.html for a number of these links.

**Comment by sarina** [comment]
As a project I feel we have made huge strides towards fundamentally-public documentation.

I don't think we should allow links to documentation that is partially private. The public stuff should go in a public, available doc (ideally OEPs, ADRs, and wiki pages as opposed to non-discoverable docs like Google Docs, Figma files, Miro boards, as much as posssible). If a certain organization requires private context around a public doc, they can create their own private document that links out to the public stuff. The public docs should be canonical, not secondary.
