### ISSUE TITLE
Build a copy of the Open edX Proposals as a subproject of docs.openedx.org

### ISSUE THREAD

**Issue by feanil** [openedx/open-edx-proposals#409]
We want the old links to keep working but we also want to host this info under the docs.openedx.org domain so that it can be searched/found with the rest of the openedx docs.

**Comment by sarina** [comment]
Yes yes!

I suspect a number of OEPs link to one another, and that numerous ADRs throughout the codebase link to OEPs, so in is much needed to keep existing links working.

**Comment by feanil** [comment]
I've added the new project in RTD at:  https://readthedocs.org/projects/openedx-proposals/

https://github.com/openedx/docs.openedx.org/pull/221 make docs.openedx.org use this new project location.

**Comment by feanil** [comment]
The changes have been merged so this should be all set.
