### ISSUE TITLE
Determine process for getting OEP-52 to Accepted

### ISSUE THREAD

**Issue by rgraber** [openedx/open-edx-proposals#415]
OEP-52 (Event bus architecture https://open-edx-proposals.readthedocs.io/en/latest/architectural-decisions/oep-0052-arch-event-bus-architecture.html) was initially marked as Provisional in line with the definition of Provisional outlined in OEP-1: https://open-edx-proposals.readthedocs.io/en/latest/processes/oep-0001.html#provisional

There is now a working implementation of the event bus being used in production on edx.org, but it is unclear if this is enough to satisfy the requirement for "viable reference examples and platform adoption" to move the OEP back into Under Review with an eye towards getting it accepted. In particular, it's unclear how far we need to be on the roadmap (https://github.com/openedx/platform-roadmap/issues/28). We have completed the Happy- and Sad-Path epics and are fairly near completion on the Production-ready event. 

If we think OEP-52 is already ready to be properly reviewed, I think the proper step would be to update this PR: https://github.com/openedx/open-edx-proposals/pull/414/files to make the status Under Review and add a new acceptance period. 

Would appreciate any thoughts on this.

**Comment by robrap** [comment]
I'm wondering if we could announce this issue with a 1-2 week review period, where we decide that OEP-52 is either accepted, or we nail down what is required to bring it to accepted. 
@blarghmatey - as the original arbiter - would you mind helping with this process? At a minimum, do you have thoughts on how we can get to acceptance? Thank you!

**Comment by rgraber** [comment]
Update: https://github.com/openedx/open-edx-proposals/pull/414/files has since been merged with no change to the status. We can have another PR to either update the follow-up work with the path to Acceptance or just change the status to Under Review.

**Comment by sarina** [comment]
@rgraber @feanil @robrap OEP-52 is marked as Accepted but has a warning box that it's Provisional. This should be fixed, which one is it?

<img width="834" alt="image" src="https://github.com/openedx/open-edx-proposals/assets/1985317/3f1fad06-b5c7-4fa6-a752-c6044fc8c630">

**Comment by robrap** [comment]
The warning is outdated and can be removed.

**Comment by sarina** [comment]
#605 removes the provisional warning
