### ISSUE TITLE
Add separate section for OEPs that are withdrawn/rejected/obselete/replaced 

### ISSUE THREAD

**Issue by kdmccormick** [openedx/open-edx-proposals#427]
* This prepares us for https://github.com/openedx/open-edx-proposals/issues/428
* If we follow OEP-1's advice on merging all OEP PRs regardless of resolution, then we'll have a bunch of irrelevant OEPs hanging around on the sidebar.
* Instead, we should break off a separate section in the sidebar for OEPs with statuses withdrawn, rejected, obselete, or replaced.
  * What should we call the section? Maybe `Archive (Inactive Proposals)`?

**Comment by kdmccormick** [comment]
Unassigning myself as I have no current plans to do this.

**Comment by sarina** [comment]
we did the thing!

<img width="302" alt="image" src="https://github.com/openedx/open-edx-proposals/assets/1985317/1bd91281-17ee-4046-964a-6bc4b9c4963f">
