### ISSUE TITLE
Possible updates to OEP-49 on Django App Patterns

### ISSUE THREAD

**Issue by robrap** [openedx/open-edx-proposals#439]
Proposal:
1. [OEP-49](https://open-edx-proposals.readthedocs.io/en/latest/architectural-decisions/oep-0049-django-app-patterns.html) could require an ADR that explains the decision for creating the app in the first place.
2. This change seems to suggest that this OEP would be better characterized as a best practice OEP, where it could be updated over time, rather than an OEP of type architecture.

**Comment by sarina** [comment]
@robrap OEP-49 has been changed to Best Practice https://docs.openedx.org/projects/openedx-proposals/en/latest/best-practices/oep-0049-django-app-patterns.html and it looks like your ADR PR merged so I'm closing this issue
