### ISSUE TITLE
Authorization best practice OEP needed

### ISSUE THREAD

**Issue by robrap** [openedx/open-edx-proposals#479]
It would be great to have an Authorization best practice OEP that works much like [OEP-4: Authentication](https://open-edx-proposals.readthedocs.io/en/latest/best-practices/oep-0042-bp-authentication.html), which is less about making decisions than being an index of ADRs, documents, and introductory text regarding our Authorization best practices.

However, at this time, those best practices may be somewhat controversial because we are lacking said document. This issue can be used to collect documentation, comments, etc. regarding this topic in preparation for some future OEP.

Here is some context of what exists today:
- A fairly recent (2023) [Platform Roadmap issue on Authorization]( https://github.com/openedx/platform-roadmap/issues/246) (Platform Roadmap).
- A library (2019) [edx-rbac used for Authorization](https://github.com/openedx/edx-rbac/blob/master/docs/how_to_guide.rst).
  - A [search of our public docs for rbac](https://docs.edx.org/search?q=rbac). 
  - A [public Confluence page on Authorization and edx-rbac](https://openedx.atlassian.net/wiki/spaces/AC/pages/935919751/Authorization)
- The very old (2016) [OEP-9: User Authorization](https://open-edx-proposals.readthedocs.io/en/latest/best-practices/oep-0009-bp-permissions.html).
  - The OEP doesn't even mention `edx-rbac`.
  - The OEP predates our use of `Provisional` status to show something aspirational.
  - It is unclear how much we are following this OEP, if at all.
  - The OEP doesn't mention the numerous ways authorization is handled today, either as Rejected/Deprecated ways or otherwise.
- Scopes documentation: 
  - Deleted [OEP on scopes ](https://github.com/openedx/open-edx-proposals/pull/10/files ) (initially merged as Under Review)
  - [ADRs 5-7,11,12](https://github.com/openedx/edx-platform/blob/master/openedx/core/djangoapps/oauth_dispatch/docs/decisions/0007-include-organizations-in-tokens.rst) in edx-platform.

**Comment by robrap** [comment]
Here is a newer [Google doc on Roles and Permissions](https://docs.google.com/document/d/1LZi5r3GYuSlrSRqfVKY1r61ysFQfaVLPJC0p-wVR-3g/edit#heading=h.xe2jv8xthu20).

**Comment by hsinkoff** [comment]
[Tech Spec](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3824648277/RBAC+Tech+Spec) related to the RBAC project.

**Comment by sarina** [comment]
I think an Authorization OEP is a good idea, but as a project we're pretty far away from it. Adding the Discovery label to it and tagging @feanil and @ormsbee to keep in the backs of our minds as we approach the R&P work.

**Comment by robrap** [comment]
I'm not sure if 100% of this is covered, but it was already completed with this OEP: https://open-edx-proposals.readthedocs.io/en/latest/best-practices/oep-0066-bp-authorization.html

**Comment by sarina** [comment]
Ha! I only saw OEP-9 in the right sidebar listed as obsolete and didn't follow the link to OEP-66. Thanks Robert!
