### ISSUE TITLE
OEP-67 - Greenkeeper is an out-of-date recommendation

### ISSUE THREAD

**Issue by feanil** [openedx/open-edx-proposals#524]
OEP-67/OEP-14 currently recommend greenkeeper to keep JS dependencies up-to-date.  This should be renotave instead.

From Jeremy Bowman:

> See https://openedx.atlassian.net/wiki/spaces/AC/pages/1841791377/Set+up+Renovate+to+Automate+JavaScript+Dependency+Updates#Notes-on-Alternatives for reasons we started to ditch Greenkeeper. As with the Redux note above we could update it after initial release, but I'd rather not risk people trying to start switching to Greenkeeper after reading this.

**Comment by jmbowman** [comment]
Note that https://openedx.atlassian.net/wiki/spaces/AC/pages/1841791377/Set+up+Renovate+to+Automate+JavaScript+Dependency+Updates has good context but stale instructions, and there is also https://docs.openedx.org/en/latest/developers/how-tos/enable-javascript-upgrade-automation.html with updated instructions but no context.  We should update, consolidate, and/or cross-link these documents.

**Comment by sarina** [comment]
@brian-smith-tcril volunteered to help usher this through in this thread: https://openedx.slack.com/archives/C04BM6YC7A6/p1715977120811569
