### ISSUE TITLE
Issue on page /processes/oep-0054-core-contributors.html

### ISSUE THREAD

**Issue by robrap** [openedx/open-edx-proposals#569]
The OEP includes two links with the same text, to different places. Maybe the text could be updated?

[Core Contributor Rights & Responsibilities](https://openedx.atlassian.net/wiki/spaces/COMM/pages/2952003698/Core+Contributor+Rights+Responsibilities+excluding+code+contributors)

[Code Committer Rights & Responsibilities](https://openedx.atlassian.net/wiki/spaces/COMM/pages/1529675973/Rights+Responsibilities+for+Code+Contributors)

**Comment by sarina** [comment]
Fixed by https://github.com/openedx/open-edx-proposals/pull/571
