### ISSUE TITLE
Amend or revoke OEPs that were not implemented

### ISSUE THREAD

**Issue by kdmccormick** [openedx/open-edx-proposals#573]
Several OEPs were authored aspirationally, and then never implemented. Other were partially implemented, but have stalled or diverged from reality.

In order to establish OEPs as a trustworthy source of documentation, we should mark OEPs that never came to be as "Replaced" or "Obsolete" (whichever or is more appropriate). We should amend OEPs that are still relevant but mismatched with reality.

Browsing https://docs.openedx.org/projects/openedx-proposals/en/latest/, ones that jump out at me are:

- [x] OEP-56 Arch Advisory Process: Never implemented.
- [ ] [OEP-37 Dev Data: Partially implemented. Should evaluate whether to carry this forward or revoke it.](https://github.com/openedx/open-edx-proposals/issues/607)
- [x] OEP-06 Context-Scoped XBlock Fields: Never implemented, no plans to implement.
- [ ] https://github.com/openedx/open-edx-proposals/issues/587

Finally, various OEPs are in the state "Provisional". At this point we should transition them to "Accepted", if appropriate.

* See https://github.com/openedx/open-edx-proposals/issues/608

**Comment by sarina** [comment]
Agreed on this. I'd be happy to help develop a plan with you - maybe we could do a working hour 1-1 in person and discuss an approach, maybe categorize a couple as well. I think that would kickstart it enough for me to run with finishing it out. If that works for you, let's aim for after we hire a data engineer.

**Comment by sarina** [comment]
Closing this issue, as finer-grained new issues have been made for the remaining work.
