### ISSUE TITLE
Broken Hooks link

### ISSUE THREAD

**Issue by sarina** [openedx/open-edx-proposals#653]
Hi @mariajgrimaldi - I think your refactoring broke a link in OEP-50. Could you please check it out?

/home/docs/checkouts/readthedocs.org/user_builds/openedx-proposals/checkouts/652/oeps/architectural-decisions/oep-0050-hooks-extension-framework.rst:39: WARNING: unknown document: 'edx-platform:hooks/index' [ref.doc]

Blocks #652

**Comment by mariajgrimaldi** [comment]
Yes!
